In [150]:
from dotenv import load_dotenv

from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chat_models import ChatOpenAI

load_dotenv()

True

In [14]:
# Load the code to analyse
loader = DirectoryLoader("source_code/sql_server", glob="**/*.sql", loader_cls=TextLoader, show_progress=True)
documents = loader.load()
documents

100%|██████████| 2/2 [00:00<00:00, 1403.25it/s]

[Document(page_content='/*\n** Copyright Microsoft, Inc. 1994 - 2000\n** All Rights Reserved.\n*/\n\n-- This script does not create a database.\n-- Run this script in the database you want the objects to be created.\n-- Default schema is dbo.\n\nSET NOCOUNT ON\nGO\n\nset quoted_identifier on\nGO\n\n/* Set DATEFORMAT so that the date strings are interpreted correctly regardless of\n   the default DATEFORMAT on the server.\n*/\nSET DATEFORMAT mdy\nGO\n\ngo\nif exists (select * from sysobjects where id = object_id(\'dbo.Employee Sales by Country\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Employee Sales by Country"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales by Year\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Sales by Year"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Ten Most Expensive Products\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Ten Most Expensive Products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrderHist\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrderHist"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrdersDetail\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrdersDetail"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrdersOrders\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrdersOrders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.SalesByCategory\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."SalesByCategory"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Category Sales for 1997\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Category Sales for 1997"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales by Category\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Sales by Category"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales Totals by Amount\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Sales Totals by Amount"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Summary of Sales by Quarter\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Summary of Sales by Quarter"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Summary of Sales by Year\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Summary of Sales by Year"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Invoices\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Invoices"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Details Extended\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Order Details Extended"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Subtotals\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Order Subtotals"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Product Sales for 1997\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Product Sales for 1997"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Alphabetical list of products\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Alphabetical list of products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Current Product List\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Current Product List"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Orders Qry\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Orders Qry"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products Above Average Price\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Products Above Average Price"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products by Category\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Products by Category"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Quarterly Orders\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Quarterly Orders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Customer and Suppliers by City\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Customer and Suppliers by City"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Details\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Order Details"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Orders\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Orders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Categories\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Categories"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustomerCustomerDemo\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."CustomerCustomerDemo"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustomerDemographics\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."CustomerDemographics"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Customers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Customers"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Shippers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Shippers"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Suppliers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Suppliers"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.EmployeeTerritories\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."EmployeeTerritories"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Territories\') and sysstat & 0xf = 3)\n\tdrop table "dbo".Territories\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Region\') and sysstat & 0xf = 3)\n\tdrop table "dbo".Region\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Employees\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Employees"\nGO\n\nCREATE TABLE "Employees" (\n\t"EmployeeID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"LastName" nvarchar (20) NOT NULL ,\n\t"FirstName" nvarchar (10) NOT NULL ,\n\t"Title" nvarchar (30) NULL ,\n\t"TitleOfCourtesy" nvarchar (25) NULL ,\n\t"BirthDate" "datetime" NULL ,\n\t"HireDate" "datetime" NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"HomePhone" nvarchar (24) NULL ,\n\t"Extension" nvarchar (4) NULL ,\n\t"Photo" "image" NULL ,\n\t"Notes" "ntext" NULL ,\n\t"ReportsTo" "int" NULL ,\n\t"PhotoPath" nvarchar (255) NULL ,\n\tCONSTRAINT "PK_Employees" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "FK_Employees_Employees" FOREIGN KEY \n\t(\n\t\t"ReportsTo"\n\t) REFERENCES "dbo"."Employees" (\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "CK_Birthdate" CHECK (BirthDate < getdate())\n)\nGO\n CREATE  INDEX "LastName" ON "dbo"."Employees"("LastName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Employees"("PostalCode")\nGO\n\nCREATE TABLE "Categories" (\n\t"CategoryID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CategoryName" nvarchar (15) NOT NULL ,\n\t"Description" "ntext" NULL ,\n\t"Picture" "image" NULL ,\n\tCONSTRAINT "PK_Categories" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"CategoryID"\n\t)\n)\nGO\n CREATE  INDEX "CategoryName" ON "dbo"."Categories"("CategoryName")\nGO\n\nCREATE TABLE "Customers" (\n\t"CustomerID" nchar (5) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"ContactName" nvarchar (30) NULL ,\n\t"ContactTitle" nvarchar (30) NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\t"Fax" nvarchar (24) NULL ,\n\tCONSTRAINT "PK_Customers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"CustomerID"\n\t)\n)\nGO\n CREATE  INDEX "City" ON "dbo"."Customers"("City")\nGO\n CREATE  INDEX "CompanyName" ON "dbo"."Customers"("CompanyName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Customers"("PostalCode")\nGO\n CREATE  INDEX "Region" ON "dbo"."Customers"("Region")\nGO\n\nCREATE TABLE "Shippers" (\n\t"ShipperID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\tCONSTRAINT "PK_Shippers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"ShipperID"\n\t)\n)\nGO\nCREATE TABLE "Suppliers" (\n\t"SupplierID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"ContactName" nvarchar (30) NULL ,\n\t"ContactTitle" nvarchar (30) NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\t"Fax" nvarchar (24) NULL ,\n\t"HomePage" "ntext" NULL ,\n\tCONSTRAINT "PK_Suppliers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"SupplierID"\n\t)\n)\nGO\n CREATE  INDEX "CompanyName" ON "dbo"."Suppliers"("CompanyName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Suppliers"("PostalCode")\nGO\n\nCREATE TABLE "Orders" (\n\t"OrderID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CustomerID" nchar (5) NULL ,\n\t"EmployeeID" "int" NULL ,\n\t"OrderDate" "datetime" NULL ,\n\t"RequiredDate" "datetime" NULL ,\n\t"ShippedDate" "datetime" NULL ,\n\t"ShipVia" "int" NULL ,\n\t"Freight" "money" NULL CONSTRAINT "DF_Orders_Freight" DEFAULT (0),\n\t"ShipName" nvarchar (40) NULL ,\n\t"ShipAddress" nvarchar (60) NULL ,\n\t"ShipCity" nvarchar (15) NULL ,\n\t"ShipRegion" nvarchar (15) NULL ,\n\t"ShipPostalCode" nvarchar (10) NULL ,\n\t"ShipCountry" nvarchar (15) NULL ,\n\tCONSTRAINT "PK_Orders" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"OrderID"\n\t),\n\tCONSTRAINT "FK_Orders_Customers" FOREIGN KEY \n\t(\n\t\t"CustomerID"\n\t) REFERENCES "dbo"."Customers" (\n\t\t"CustomerID"\n\t),\n\tCONSTRAINT "FK_Orders_Employees" FOREIGN KEY \n\t(\n\t\t"EmployeeID"\n\t) REFERENCES "dbo"."Employees" (\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "FK_Orders_Shippers" FOREIGN KEY \n\t(\n\t\t"ShipVia"\n\t) REFERENCES "dbo"."Shippers" (\n\t\t"ShipperID"\n\t)\n)\nGO\n CREATE  INDEX "CustomerID" ON "dbo"."Orders"("CustomerID")\nGO\n CREATE  INDEX "CustomersOrders" ON "dbo"."Orders"("CustomerID")\nGO\n CREATE  INDEX "EmployeeID" ON "dbo"."Orders"("EmployeeID")\nGO\n CREATE  INDEX "EmployeesOrders" ON "dbo"."Orders"("EmployeeID")\nGO\n CREATE  INDEX "OrderDate" ON "dbo"."Orders"("OrderDate")\nGO\n CREATE  INDEX "ShippedDate" ON "dbo"."Orders"("ShippedDate")\nGO\n CREATE  INDEX "ShippersOrders" ON "dbo"."Orders"("ShipVia")\nGO\n CREATE  INDEX "ShipPostalCode" ON "dbo"."Orders"("ShipPostalCode")\nGO\n\nCREATE TABLE "Products" (\n\t"ProductID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"ProductName" nvarchar (40) NOT NULL ,\n\t"SupplierID" "int" NULL ,\n\t"CategoryID" "int" NULL ,\n\t"QuantityPerUnit" nvarchar (20) NULL ,\n\t"UnitPrice" "money" NULL CONSTRAINT "DF_Products_UnitPrice" DEFAULT (0),\n\t"UnitsInStock" "smallint" NULL CONSTRAINT "DF_Products_UnitsInStock" DEFAULT (0),\n\t"UnitsOnOrder" "smallint" NULL CONSTRAINT "DF_Products_UnitsOnOrder" DEFAULT (0),\n\t"ReorderLevel" "smallint" NULL CONSTRAINT "DF_Products_ReorderLevel" DEFAULT (0),\n\t"Discontinued" "bit" NOT NULL CONSTRAINT "DF_Products_Discontinued" DEFAULT (0),\n\tCONSTRAINT "PK_Products" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "FK_Products_Categories" FOREIGN KEY \n\t(\n\t\t"CategoryID"\n\t) REFERENCES "dbo"."Categories" (\n\t\t"CategoryID"\n\t),\n\tCONSTRAINT "FK_Products_Suppliers" FOREIGN KEY \n\t(\n\t\t"SupplierID"\n\t) REFERENCES "dbo"."Suppliers" (\n\t\t"SupplierID"\n\t),\n\tCONSTRAINT "CK_Products_UnitPrice" CHECK (UnitPrice >= 0),\n\tCONSTRAINT "CK_ReorderLevel" CHECK (ReorderLevel >= 0),\n\tCONSTRAINT "CK_UnitsInStock" CHECK (UnitsInStock >= 0),\n\tCONSTRAINT "CK_UnitsOnOrder" CHECK (UnitsOnOrder >= 0)\n)\nGO\n CREATE  INDEX "CategoriesProducts" ON "dbo"."Products"("CategoryID")\nGO\n CREATE  INDEX "CategoryID" ON "dbo"."Products"("CategoryID")\nGO\n CREATE  INDEX "ProductName" ON "dbo"."Products"("ProductName")\nGO\n CREATE  INDEX "SupplierID" ON "dbo"."Products"("SupplierID")\nGO\n CREATE  INDEX "SuppliersProducts" ON "dbo"."Products"("SupplierID")\nGO\n\nCREATE TABLE "Order Details" (\n\t"OrderID" "int" NOT NULL ,\n\t"ProductID" "int" NOT NULL ,\n\t"UnitPrice" "money" NOT NULL CONSTRAINT "DF_Order_Details_UnitPrice" DEFAULT (0),\n\t"Quantity" "smallint" NOT NULL CONSTRAINT "DF_Order_Details_Quantity" DEFAULT (1),\n\t"Discount" "real" NOT NULL CONSTRAINT "DF_Order_Details_Discount" DEFAULT (0),\n\tCONSTRAINT "PK_Order_Details" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"OrderID",\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "FK_Order_Details_Orders" FOREIGN KEY \n\t(\n\t\t"OrderID"\n\t) REFERENCES "dbo"."Orders" (\n\t\t"OrderID"\n\t),\n\tCONSTRAINT "FK_Order_Details_Products" FOREIGN KEY \n\t(\n\t\t"ProductID"\n\t) REFERENCES "dbo"."Products" (\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "CK_Discount" CHECK (Discount >= 0 and (Discount <= 1)),\n\tCONSTRAINT "CK_Quantity" CHECK (Quantity > 0),\n\tCONSTRAINT "CK_UnitPrice" CHECK (UnitPrice >= 0)\n)\nGO\n CREATE  INDEX "OrderID" ON "dbo"."Order Details"("OrderID")\nGO\n CREATE  INDEX "OrdersOrder_Details" ON "dbo"."Order Details"("OrderID")\nGO\n CREATE  INDEX "ProductID" ON "dbo"."Order Details"("ProductID")\nGO\n CREATE  INDEX "ProductsOrder_Details" ON "dbo"."Order Details"("ProductID")\nGO\n\n\ncreate view "Customer and Suppliers by City" AS\nSELECT City, CompanyName, ContactName, \'Customers\' AS Relationship \nFROM Customers\nUNION SELECT City, CompanyName, ContactName, \'Suppliers\'\nFROM Suppliers\n--ORDER BY City, CompanyName\nGO\n\ncreate view "Alphabetical list of products" AS\nSELECT Products.*, Categories.CategoryName\nFROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID\nWHERE (((Products.Discontinued)=0))\nGO\n\ncreate view "Current Product List" AS\nSELECT Product_List.ProductID, Product_List.ProductName\nFROM Products AS Product_List\nWHERE (((Product_List.Discontinued)=0))\n--ORDER BY Product_List.ProductName\nGO\n\ncreate view "Orders Qry" AS\nSELECT Orders.OrderID, Orders.CustomerID, Orders.EmployeeID, Orders.OrderDate, Orders.RequiredDate, \n\tOrders.ShippedDate, Orders.ShipVia, Orders.Freight, Orders.ShipName, Orders.ShipAddress, Orders.ShipCity, \n\tOrders.ShipRegion, Orders.ShipPostalCode, Orders.ShipCountry, \n\tCustomers.CompanyName, Customers.Address, Customers.City, Customers.Region, Customers.PostalCode, Customers.Country\nFROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID\nGO\n\ncreate view "Products Above Average Price" AS\nSELECT Products.ProductName, Products.UnitPrice\nFROM Products\nWHERE Products.UnitPrice>(SELECT AVG(UnitPrice) From Products)\n--ORDER BY Products.UnitPrice DESC\nGO\n\ncreate view "Products by Category" AS\nSELECT Categories.CategoryName, Products.ProductName, Products.QuantityPerUnit, Products.UnitsInStock, Products.Discontinued\nFROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID\nWHERE Products.Discontinued <> 1\n--ORDER BY Categories.CategoryName, Products.ProductName\nGO\n\ncreate view "Quarterly Orders" AS\nSELECT DISTINCT Customers.CustomerID, Customers.CompanyName, Customers.City, Customers.Country\nFROM Customers RIGHT JOIN Orders ON Customers.CustomerID = Orders.CustomerID\nWHERE Orders.OrderDate BETWEEN \'19970101\' And \'19971231\'\nGO\n\ncreate view Invoices AS\nSELECT Orders.ShipName, Orders.ShipAddress, Orders.ShipCity, Orders.ShipRegion, Orders.ShipPostalCode, \n\tOrders.ShipCountry, Orders.CustomerID, Customers.CompanyName AS CustomerName, Customers.Address, Customers.City, \n\tCustomers.Region, Customers.PostalCode, Customers.Country, \n\t(FirstName + \' \' + LastName) AS Salesperson, \n\tOrders.OrderID, Orders.OrderDate, Orders.RequiredDate, Orders.ShippedDate, Shippers.CompanyName As ShipperName, \n\t"Order Details".ProductID, Products.ProductName, "Order Details".UnitPrice, "Order Details".Quantity, \n\t"Order Details".Discount, \n\t(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ExtendedPrice, Orders.Freight\nFROM \tShippers INNER JOIN \n\t\t(Products INNER JOIN \n\t\t\t(\n\t\t\t\t(Employees INNER JOIN \n\t\t\t\t\t(Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID) \n\t\t\t\tON Employees.EmployeeID = Orders.EmployeeID) \n\t\t\tINNER JOIN "Order Details" ON Orders.OrderID = "Order Details".OrderID) \n\t\tON Products.ProductID = "Order Details".ProductID) \n\tON Shippers.ShipperID = Orders.ShipVia\nGO\n\ncreate view "Order Details Extended" AS\nSELECT "Order Details".OrderID, "Order Details".ProductID, Products.ProductName, \n\t"Order Details".UnitPrice, "Order Details".Quantity, "Order Details".Discount, \n\t(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ExtendedPrice\nFROM Products INNER JOIN "Order Details" ON Products.ProductID = "Order Details".ProductID\n--ORDER BY "Order Details".OrderID\nGO\n\ncreate view "Order Subtotals" AS\nSELECT "Order Details".OrderID, Sum(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS Subtotal\nFROM "Order Details"\nGROUP BY "Order Details".OrderID\nGO\n\ncreate view "Product Sales for 1997" AS\nSELECT Categories.CategoryName, Products.ProductName, \nSum(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ProductSales\nFROM (Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID) \n\tINNER JOIN (Orders \n\t\tINNER JOIN "Order Details" ON Orders.OrderID = "Order Details".OrderID) \n\tON Products.ProductID = "Order Details".ProductID\nWHERE (((Orders.ShippedDate) Between \'19970101\' And \'19971231\'))\nGROUP BY Categories.CategoryName, Products.ProductName\nGO\n\ncreate view "Category Sales for 1997" AS\nSELECT "Product Sales for 1997".CategoryName, Sum("Product Sales for 1997".ProductSales) AS CategorySales\nFROM "Product Sales for 1997"\nGROUP BY "Product Sales for 1997".CategoryName\nGO\n\ncreate view "Sales by Category" AS\nSELECT Categories.CategoryID, Categories.CategoryName, Products.ProductName, \n\tSum("Order Details Extended".ExtendedPrice) AS ProductSales\nFROM \tCategories INNER JOIN \n\t\t(Products INNER JOIN \n\t\t\t(Orders INNER JOIN "Order Details Extended" ON Orders.OrderID = "Order Details Extended".OrderID) \n\t\tON Products.ProductID = "Order Details Extended".ProductID) \n\tON Categories.CategoryID = Products.CategoryID\nWHERE Orders.OrderDate BETWEEN \'19970101\' And \'19971231\'\nGROUP BY Categories.CategoryID, Categories.CategoryName, Products.ProductName\n--ORDER BY Products.ProductName\nGO\n\ncreate view "Sales Totals by Amount" AS\nSELECT "Order Subtotals".Subtotal AS SaleAmount, Orders.OrderID, Customers.CompanyName, Orders.ShippedDate\nFROM \tCustomers INNER JOIN \n\t\t(Orders INNER JOIN "Order Subtotals" ON Orders.OrderID = "Order Subtotals".OrderID) \n\tON Customers.CustomerID = Orders.CustomerID\nWHERE ("Order Subtotals".Subtotal >2500) AND (Orders.ShippedDate BETWEEN \'19970101\' And \'19971231\')\nGO\n\ncreate view "Summary of Sales by Quarter" AS\nSELECT Orders.ShippedDate, Orders.OrderID, "Order Subtotals".Subtotal\nFROM Orders INNER JOIN "Order Subtotals" ON Orders.OrderID = "Order Subtotals".OrderID\nWHERE Orders.ShippedDate IS NOT NULL\n--ORDER BY Orders.ShippedDate\nGO\n\ncreate view "Summary of Sales by Year" AS\nSELECT Orders.ShippedDate, Orders.OrderID, "Order Subtotals".Subtotal\nFROM Orders INNER JOIN "Order Subtotals" ON Orders.OrderID = "Order Subtotals".OrderID\nWHERE Orders.ShippedDate IS NOT NULL\n--ORDER BY Orders.ShippedDate\nGO\n\ncreate procedure "Ten Most Expensive Products" AS\nSET ROWCOUNT 10\nSELECT Products.ProductName AS TenMostExpensiveProducts, Products.UnitPrice\nFROM Products\nORDER BY Products.UnitPrice DESC\nGO\n\ncreate procedure "Employee Sales by Country" \n@Beginning_Date DateTime, @Ending_Date DateTime AS\nSELECT Employees.Country, Employees.LastName, Employees.FirstName, Orders.ShippedDate, 

In [15]:
splitter = RecursiveCharacterTextSplitter(separators=["GO\n", "\n\n", "\n"], chunk_size=2500, chunk_overlap=0)
chunks = splitter.split_documents(documents)
chunks

[Document(page_content='/*\n** Copyright Microsoft, Inc. 1994 - 2000\n** All Rights Reserved.\n*/\n\n-- This script does not create a database.\n-- Run this script in the database you want the objects to be created.\n-- Default schema is dbo.\n\nSET NOCOUNT ON\nGO\n\nset quoted_identifier on\nGO\n\n/* Set DATEFORMAT so that the date strings are interpreted correctly regardless of\n   the default DATEFORMAT on the server.\n*/\nSET DATEFORMAT mdy\nGO\n\ngo\nif exists (select * from sysobjects where id = object_id(\'dbo.Employee Sales by Country\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Employee Sales by Country"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales by Year\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Sales by Year"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Ten Most Expensive Products\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."Ten Most Expensive Products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrderHist\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrderHist"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrdersDetail\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrdersDetail"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustOrdersOrders\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."CustOrdersOrders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.SalesByCategory\') and sysstat & 0xf = 4)\n\tdrop procedure "dbo"."SalesByCategory"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Category Sales for 1997\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Category Sales for 1997"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales by Category\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Sales by Category"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Sales Totals by Amount\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Sales Totals by Amount"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Summary of Sales by Quarter\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Summary of Sales by Quarter"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Summary of Sales by Year\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Summary of Sales by Year"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Invoices\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Invoices"', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Details Extended\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Order Details Extended"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Subtotals\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Order Subtotals"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Product Sales for 1997\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Product Sales for 1997"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Alphabetical list of products\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Alphabetical list of products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Current Product List\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Current Product List"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Orders Qry\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Orders Qry"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products Above Average Price\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Products Above Average Price"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products by Category\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Products by Category"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Quarterly Orders\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Quarterly Orders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Customer and Suppliers by City\') and sysstat & 0xf = 2)\n\tdrop view "dbo"."Customer and Suppliers by City"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Order Details\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Order Details"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Orders\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Orders"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Products\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Products"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Categories\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Categories"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustomerCustomerDemo\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."CustomerCustomerDemo"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.CustomerDemographics\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."CustomerDemographics"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Customers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Customers"', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\nif exists (select * from sysobjects where id = object_id(\'dbo.Shippers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Shippers"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Suppliers\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Suppliers"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.EmployeeTerritories\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."EmployeeTerritories"\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Territories\') and sysstat & 0xf = 3)\n\tdrop table "dbo".Territories\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Region\') and sysstat & 0xf = 3)\n\tdrop table "dbo".Region\nGO\nif exists (select * from sysobjects where id = object_id(\'dbo.Employees\') and sysstat & 0xf = 3)\n\tdrop table "dbo"."Employees"\nGO\n\nCREATE TABLE "Employees" (\n\t"EmployeeID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"LastName" nvarchar (20) NOT NULL ,\n\t"FirstName" nvarchar (10) NOT NULL ,\n\t"Title" nvarchar (30) NULL ,\n\t"TitleOfCourtesy" nvarchar (25) NULL ,\n\t"BirthDate" "datetime" NULL ,\n\t"HireDate" "datetime" NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"HomePhone" nvarchar (24) NULL ,\n\t"Extension" nvarchar (4) NULL ,\n\t"Photo" "image" NULL ,\n\t"Notes" "ntext" NULL ,\n\t"ReportsTo" "int" NULL ,\n\t"PhotoPath" nvarchar (255) NULL ,\n\tCONSTRAINT "PK_Employees" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "FK_Employees_Employees" FOREIGN KEY \n\t(\n\t\t"ReportsTo"\n\t) REFERENCES "dbo"."Employees" (\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "CK_Birthdate" CHECK (BirthDate < getdate())\n)\nGO\n CREATE  INDEX "LastName" ON "dbo"."Employees"("LastName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Employees"("PostalCode")\nGO\n\nCREATE TABLE "Categories" (\n\t"CategoryID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CategoryName" nvarchar (15) NOT NULL ,\n\t"Description" "ntext" NULL ,\n\t"Picture" "image" NULL ,\n\tCONSTRAINT "PK_Categories" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"CategoryID"\n\t)\n)\nGO\n CREATE  INDEX "CategoryName" ON "dbo"."Categories"("CategoryName")', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\n\nCREATE TABLE "Customers" (\n\t"CustomerID" nchar (5) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"ContactName" nvarchar (30) NULL ,\n\t"ContactTitle" nvarchar (30) NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\t"Fax" nvarchar (24) NULL ,\n\tCONSTRAINT "PK_Customers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"CustomerID"\n\t)\n)\nGO\n CREATE  INDEX "City" ON "dbo"."Customers"("City")\nGO\n CREATE  INDEX "CompanyName" ON "dbo"."Customers"("CompanyName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Customers"("PostalCode")\nGO\n CREATE  INDEX "Region" ON "dbo"."Customers"("Region")\nGO\n\nCREATE TABLE "Shippers" (\n\t"ShipperID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\tCONSTRAINT "PK_Shippers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"ShipperID"\n\t)\n)\nGO\nCREATE TABLE "Suppliers" (\n\t"SupplierID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CompanyName" nvarchar (40) NOT NULL ,\n\t"ContactName" nvarchar (30) NULL ,\n\t"ContactTitle" nvarchar (30) NULL ,\n\t"Address" nvarchar (60) NULL ,\n\t"City" nvarchar (15) NULL ,\n\t"Region" nvarchar (15) NULL ,\n\t"PostalCode" nvarchar (10) NULL ,\n\t"Country" nvarchar (15) NULL ,\n\t"Phone" nvarchar (24) NULL ,\n\t"Fax" nvarchar (24) NULL ,\n\t"HomePage" "ntext" NULL ,\n\tCONSTRAINT "PK_Suppliers" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"SupplierID"\n\t)\n)\nGO\n CREATE  INDEX "CompanyName" ON "dbo"."Suppliers"("CompanyName")\nGO\n CREATE  INDEX "PostalCode" ON "dbo"."Suppliers"("PostalCode")', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\n\nCREATE TABLE "Orders" (\n\t"OrderID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"CustomerID" nchar (5) NULL ,\n\t"EmployeeID" "int" NULL ,\n\t"OrderDate" "datetime" NULL ,\n\t"RequiredDate" "datetime" NULL ,\n\t"ShippedDate" "datetime" NULL ,\n\t"ShipVia" "int" NULL ,\n\t"Freight" "money" NULL CONSTRAINT "DF_Orders_Freight" DEFAULT (0),\n\t"ShipName" nvarchar (40) NULL ,\n\t"ShipAddress" nvarchar (60) NULL ,\n\t"ShipCity" nvarchar (15) NULL ,\n\t"ShipRegion" nvarchar (15) NULL ,\n\t"ShipPostalCode" nvarchar (10) NULL ,\n\t"ShipCountry" nvarchar (15) NULL ,\n\tCONSTRAINT "PK_Orders" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"OrderID"\n\t),\n\tCONSTRAINT "FK_Orders_Customers" FOREIGN KEY \n\t(\n\t\t"CustomerID"\n\t) REFERENCES "dbo"."Customers" (\n\t\t"CustomerID"\n\t),\n\tCONSTRAINT "FK_Orders_Employees" FOREIGN KEY \n\t(\n\t\t"EmployeeID"\n\t) REFERENCES "dbo"."Employees" (\n\t\t"EmployeeID"\n\t),\n\tCONSTRAINT "FK_Orders_Shippers" FOREIGN KEY \n\t(\n\t\t"ShipVia"\n\t) REFERENCES "dbo"."Shippers" (\n\t\t"ShipperID"\n\t)\n)\nGO\n CREATE  INDEX "CustomerID" ON "dbo"."Orders"("CustomerID")\nGO\n CREATE  INDEX "CustomersOrders" ON "dbo"."Orders"("CustomerID")\nGO\n CREATE  INDEX "EmployeeID" ON "dbo"."Orders"("EmployeeID")\nGO\n CREATE  INDEX "EmployeesOrders" ON "dbo"."Orders"("EmployeeID")\nGO\n CREATE  INDEX "OrderDate" ON "dbo"."Orders"("OrderDate")\nGO\n CREATE  INDEX "ShippedDate" ON "dbo"."Orders"("ShippedDate")\nGO\n CREATE  INDEX "ShippersOrders" ON "dbo"."Orders"("ShipVia")\nGO\n CREATE  INDEX "ShipPostalCode" ON "dbo"."Orders"("ShipPostalCode")', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\n\nCREATE TABLE "Products" (\n\t"ProductID" "int" IDENTITY (1, 1) NOT NULL ,\n\t"ProductName" nvarchar (40) NOT NULL ,\n\t"SupplierID" "int" NULL ,\n\t"CategoryID" "int" NULL ,\n\t"QuantityPerUnit" nvarchar (20) NULL ,\n\t"UnitPrice" "money" NULL CONSTRAINT "DF_Products_UnitPrice" DEFAULT (0),\n\t"UnitsInStock" "smallint" NULL CONSTRAINT "DF_Products_UnitsInStock" DEFAULT (0),\n\t"UnitsOnOrder" "smallint" NULL CONSTRAINT "DF_Products_UnitsOnOrder" DEFAULT (0),\n\t"ReorderLevel" "smallint" NULL CONSTRAINT "DF_Products_ReorderLevel" DEFAULT (0),\n\t"Discontinued" "bit" NOT NULL CONSTRAINT "DF_Products_Discontinued" DEFAULT (0),\n\tCONSTRAINT "PK_Products" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "FK_Products_Categories" FOREIGN KEY \n\t(\n\t\t"CategoryID"\n\t) REFERENCES "dbo"."Categories" (\n\t\t"CategoryID"\n\t),\n\tCONSTRAINT "FK_Products_Suppliers" FOREIGN KEY \n\t(\n\t\t"SupplierID"\n\t) REFERENCES "dbo"."Suppliers" (\n\t\t"SupplierID"\n\t),\n\tCONSTRAINT "CK_Products_UnitPrice" CHECK (UnitPrice >= 0),\n\tCONSTRAINT "CK_ReorderLevel" CHECK (ReorderLevel >= 0),\n\tCONSTRAINT "CK_UnitsInStock" CHECK (UnitsInStock >= 0),\n\tCONSTRAINT "CK_UnitsOnOrder" CHECK (UnitsOnOrder >= 0)\n)\nGO\n CREATE  INDEX "CategoriesProducts" ON "dbo"."Products"("CategoryID")\nGO\n CREATE  INDEX "CategoryID" ON "dbo"."Products"("CategoryID")\nGO\n CREATE  INDEX "ProductName" ON "dbo"."Products"("ProductName")\nGO\n CREATE  INDEX "SupplierID" ON "dbo"."Products"("SupplierID")\nGO\n CREATE  INDEX "SuppliersProducts" ON "dbo"."Products"("SupplierID")\nGO\n\nCREATE TABLE "Order Details" (\n\t"OrderID" "int" NOT NULL ,\n\t"ProductID" "int" NOT NULL ,\n\t"UnitPrice" "money" NOT NULL CONSTRAINT "DF_Order_Details_UnitPrice" DEFAULT (0),\n\t"Quantity" "smallint" NOT NULL CONSTRAINT "DF_Order_Details_Quantity" DEFAULT (1),\n\t"Discount" "real" NOT NULL CONSTRAINT "DF_Order_Details_Discount" DEFAULT (0),\n\tCONSTRAINT "PK_Order_Details" PRIMARY KEY  CLUSTERED \n\t(\n\t\t"OrderID",\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "FK_Order_Details_Orders" FOREIGN KEY \n\t(\n\t\t"OrderID"\n\t) REFERENCES "dbo"."Orders" (\n\t\t"OrderID"\n\t),\n\tCONSTRAINT "FK_Order_Details_Products" FOREIGN KEY \n\t(\n\t\t"ProductID"\n\t) REFERENCES "dbo"."Products" (\n\t\t"ProductID"\n\t),\n\tCONSTRAINT "CK_Discount" CHECK (Discount >= 0 and (Discount <= 1)),\n\tCONSTRAINT "CK_Quantity" CHECK (Quantity > 0),\n\tCONSTRAINT "CK_UnitPrice" CHECK (UnitPrice >= 0)\n)\nGO\n CREATE  INDEX "OrderID" ON "dbo"."Order Details"("OrderID")\nGO\n CREATE  INDEX "OrdersOrder_Details" ON "dbo"."Order Details"("OrderID")', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\n CREATE  INDEX "ProductID" ON "dbo"."Order Details"("ProductID")\nGO\n CREATE  INDEX "ProductsOrder_Details" ON "dbo"."Order Details"("ProductID")\nGO\n\n\ncreate view "Customer and Suppliers by City" AS\nSELECT City, CompanyName, ContactName, \'Customers\' AS Relationship \nFROM Customers\nUNION SELECT City, CompanyName, ContactName, \'Suppliers\'\nFROM Suppliers\n--ORDER BY City, CompanyName\nGO\n\ncreate view "Alphabetical list of products" AS\nSELECT Products.*, Categories.CategoryName\nFROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID\nWHERE (((Products.Discontinued)=0))\nGO\n\ncreate view "Current Product List" AS\nSELECT Product_List.ProductID, Product_List.ProductName\nFROM Products AS Product_List\nWHERE (((Product_List.Discontinued)=0))\n--ORDER BY Product_List.ProductName\nGO\n\ncreate view "Orders Qry" AS\nSELECT Orders.OrderID, Orders.CustomerID, Orders.EmployeeID, Orders.OrderDate, Orders.RequiredDate, \n\tOrders.ShippedDate, Orders.ShipVia, Orders.Freight, Orders.ShipName, Orders.ShipAddress, Orders.ShipCity, \n\tOrders.ShipRegion, Orders.ShipPostalCode, Orders.ShipCountry, \n\tCustomers.CompanyName, Customers.Address, Customers.City, Customers.Region, Customers.PostalCode, Customers.Country\nFROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID\nGO\n\ncreate view "Products Above Average Price" AS\nSELECT Products.ProductName, Products.UnitPrice\nFROM Products\nWHERE Products.UnitPrice>(SELECT AVG(UnitPrice) From Products)\n--ORDER BY Products.UnitPrice DESC\nGO\n\ncreate view "Products by Category" AS\nSELECT Categories.CategoryName, Products.ProductName, Products.QuantityPerUnit, Products.UnitsInStock, Products.Discontinued\nFROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID\nWHERE Products.Discontinued <> 1\n--ORDER BY Categories.CategoryName, Products.ProductName\nGO\n\ncreate view "Quarterly Orders" AS\nSELECT DISTINCT Customers.CustomerID, Customers.CompanyName, Customers.City, Customers.Country\nFROM Customers RIGHT JOIN Orders ON Customers.CustomerID = Orders.CustomerID\nWHERE Orders.OrderDate BETWEEN \'19970101\' And \'19971231\'', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),
 Document(page_content='GO\n\ncreate view Invoices AS\nSELECT Orders.ShipName, Orders.ShipAddress, Orders.ShipCity, Orders.ShipRegion, Orders.ShipPostalCode, \n\tOrders.ShipCountry, Orders.CustomerID, Customers.CompanyName AS CustomerName, Customers.Address, Customers.City, \n\tCustomers.Region, Customers.PostalCode, Customers.Country, \n\t(FirstName + \' \' + LastName) AS Salesperson, \n\tOrders.OrderID, Orders.OrderDate, Orders.RequiredDate, Orders.ShippedDate, Shippers.CompanyName As ShipperName, \n\t"Order Details".ProductID, Products.ProductName, "Order Details".UnitPrice, "Order Details".Quantity, \n\t"Order Details".Discount, \n\t(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ExtendedPrice, Orders.Freight\nFROM \tShippers INNER JOIN \n\t\t(Products INNER JOIN \n\t\t\t(\n\t\t\t\t(Employees INNER JOIN \n\t\t\t\t\t(Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID) \n\t\t\t\tON Employees.EmployeeID = Orders.EmployeeID) \n\t\t\tINNER JOIN "Order Details" ON Orders.OrderID = "Order Details".OrderID) \n\t\tON Products.ProductID = "Order Details".ProductID) \n\tON Shippers.ShipperID = Orders.ShipVia\nGO\n\ncreate view "Order Details Extended" AS\nSELECT "Order Details".OrderID, "Order Details".ProductID, Products.ProductName, \n\t"Order Details".UnitPrice, "Order Details".Quantity, "Order Details".Discount, \n\t(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ExtendedPrice\nFROM Products INNER JOIN "Order Details" ON Products.ProductID = "Order Details".ProductID\n--ORDER BY "Order Details".OrderID\nGO\n\ncreate view "Order Subtotals" AS\nSELECT "Order Details".OrderID, Sum(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS Subtotal\nFROM "Order Details"\nGROUP BY "Order Details".OrderID\nGO\n\ncreate view "Product Sales for 1997" AS\nSELECT Categories.CategoryName, Products.ProductName, \nSum(CONVERT(money,("Order Details".UnitPrice*Quantity*(1-Discount)/100))*100) AS ProductSales\nFROM (Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID) \n\tINNER JOIN (Orders \n\t\tINNER JOIN "Order Details" ON Orders.OrderID = "Order Details".OrderID) \n\tON Products.ProductID = "Order Details".ProductID\nWHERE (((Orders.ShippedDate) Between \'19970101\' And \'19971231\'))\nGROUP BY Categories.CategoryName, Products.ProductName', metadata={'source': 'source_code/sql_server/instnwnd.sql'}),

In [16]:
embeddings = OpenAIEmbeddings()
docsearch = Chroma.from_documents(chunks, embeddings)

In [179]:
llm = OpenAI(temperature=0, verbose=True)
# llm = OpenAI(model="ada", temperature=0, max_tokens=2049, verbose=True)
# llm = OpenAI(model="text-davinci-003", temperature=0, verbose=True)
# llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0, verbose=True)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=docsearch.as_retriever()
)

In [180]:
def fetch_procs():
    query = """
As a Microsoft SQL server programmer reading ANSI-SQL, list all the stored procedure names.  Note that procedure names can also have spaces within the name, as long as the name is in quotes.

Output:
procedure_name, procedure_name, procedure_name, ...
"""
    print("Query: ", query)
    ans = qa.run(query)
    print("Answer: ", ans)
    list = ans.split(',')
    return list

In [181]:
procedures = fetch_procs()
procedures

Query:
As a Microsoft SQL server programmer reading ANSI-SQL, list all the stored procedure names.  Note that procedure names can also have spaces within the name, as long as the name is in quotes.

Output:
procedure_name, procedure_name, procedure_name, ...

Answer:
"Sales by Year", CustOrdersDetail, CustOrdersOrders, CustOrderHist, SalesByCategory, reptq1, reptq2, reptq3, SalesByCategory, "Ten Most Expensive Products", "Employee Sales by Country"

['\n"Sales by Year"',
 ' CustOrdersDetail',
 ' CustOrdersOrders',
 ' CustOrderHist',
 ' SalesByCategory',
 ' reptq1',
 ' reptq2',
 ' reptq3',
 ' SalesByCategory',
 ' "Ten Most Expensive Products"',
 ' "Employee Sales by Country"']

In [165]:
for proc in procedures:
    print(proc)

CustOrdersDetail
 CustOrdersOrders
 CustOrderHist
 SalesByCategory
 byroyalty
 reptq1
 reptq2
 reptq3
 "Ten Most Expensive Products"
 "Employee Sales by Country"

In [139]:

def fetch_tables_called_by_proc(procedure_name):
    print("Getting Tables for: ", procedure_name)

    prompt = PromptTemplate(
        input_variables=["procedure_name"],
        template="""
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called {procedure_name}.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...
        """
    )
    query = prompt.format(procedure_name=procedure_name)
    ans = qa.run(query)
    print("Query: ", query)
    print("Answer: ", ans)
    list = ans.split(',')
    return list

In [166]:
print(fetch_tables_called_by_proc("CustOrdersOrders"))

Getting Tables for:  CustOrdersOrders
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called CustOrdersOrders.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  Orders
['Orders']

In [167]:

tables_by_procedure_struct = {}
for proc in procedures:
    tables_by_procedure_struct[proc] = fetch_tables_called_by_proc(proc)

Getting Tables for:  CustOrdersDetail
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called CustOrdersDetail.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  "Products", "[Order Details]"
Getting Tables for:   CustOrdersOrders
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  CustOrdersOrders.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  The stored procedure "CustOrdersOrders" queries the "Orders" table.
Getting Tables for:   CustOrderHist
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  CustOrderHist.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  The tables queried by the stored procedure CustOrderHist are:

- Products
- [Order Details]
- Orders
- Customers
Getting Tables for:   SalesByCategory
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  SalesByCategory.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  [Order Details], Orders, Products, Categories
Getting Tables for:   byroyalty
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  byroyalty.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  titleauthor, titleauthor
Getting Tables for:   reptq1
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  reptq1.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  titles
Getting Tables for:   reptq2
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  reptq2.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  The stored procedure "reptq2" queries the following tables:

- titles
- Categories
- Products
- Orders
- "Order Details Extended"
Getting Tables for:   reptq3
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  reptq3.

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  titles
Getting Tables for:   "Ten Most Expensive Products"
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  "Ten Most Expensive Products".

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  Based on the given context, the stored procedure "Ten Most Expensive Products" only queries the "Products" table. Therefore, the output would be:

Products
Getting Tables for:   "Employee Sales by Country"
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables queried or updated by the stored procedure called  "Employee Sales by Country".

            Don't list table names unless they occur within the FROM or INTO clauses of a SELECT or UPDATE statement.

            Output:
            table_name, table_name, table_name, ...

Answer:  Orders, "Order Subtotals", Employees

In [168]:
tables_by_procedure_struct

{'CustOrdersDetail': ['"Products"', ' "[Order Details]"'],
 ' CustOrdersOrders': ['The stored procedure "CustOrdersOrders" queries the "Orders" table.'],
 ' CustOrderHist': ['The tables queried by the stored procedure CustOrderHist are:\n\n- Products\n- [Order Details]\n- Orders\n- Customers'],
 ' SalesByCategory': ['[Order Details]',
  ' Orders',
  ' Products',
  ' Categories'],
 ' byroyalty': ['titleauthor', ' titleauthor'],
 ' reptq1': ['titles'],
 ' reptq2': ['The stored procedure "reptq2" queries the following tables:\n\n- titles\n- Categories\n- Products\n- Orders\n- "Order Details Extended"'],
 ' reptq3': ['titles'],
 ' "Ten Most Expensive Products"': ['Based on the given context',
  ' the stored procedure "Ten Most Expensive Products" only queries the "Products" table. Therefore',
  ' the output would be:\n\nProducts'],
 ' "Employee Sales by Country"': ['Orders',
  ' "Order Subtotals"',
  ' Employees']}

In [169]:
def fetch_tables():
    query = """
As a Microsoft SQL Server syntax parser, find all the CREATE TABLE statements and list all the table names.

Table names can be a single word, or several words that are surrounded by quotes or square brackets.

Example:
CREATE TABLE TableName
Name: TableName

Example:
CREATE TABLE "Table Name"
Name: "Table Name"

Example:
CREATE TABLE "TableName"
Name: TableName

Example:
CREATE TABLE [dbo].[TableName]
Name: TableName

Example:
CREATE TABLE [Table Name]
Name: "Table Name"

Example:
CREATE TABLE [TableName]
Name: TableName


Output:
"TableName", "TableName", "TableName", ...
"""
    print("Query: ", query)
    ans = qa.run(query)
    print("Answer: ", ans)
    list = ans.split(',')
    return list

In [171]:
tables = fetch_tables()
tables

Query:
As a Microsoft SQL Server syntax parser, find all the CREATE TABLE statements and list all the table names.

Table names can be a single word, or several words that are surrounded by quotes or square brackets.

Example:
CREATE TABLE TableName
Name: TableName

Example:
CREATE TABLE "Table Name"
Name: "Table Name"

Example:
CREATE TABLE "TableName"
Name: TableName

Example:
CREATE TABLE [dbo].[TableName]
Name: TableName

Example:
CREATE TABLE [Table Name]
Name: "Table Name"

Example:
CREATE TABLE [TableName]
Name: TableName


Output:
"TableName", "TableName", "TableName", ...

Answer:  Table Names: "Employees", "Categories", "Customers", "Shippers", "Suppliers"

['Table Names: "Employees"',
 ' "Categories"',
 ' "Customers"',
 ' "Shippers"',
 ' "Suppliers"']

In [172]:
def fetch_foreign_keys_for_table(table_name):
    print("Getting FKs for Table: ", table_name)

    prompt = PromptTemplate(
        input_variables=["table_name"],
        template="""
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables that have a foreign key foreign key constraint that references the {table_name} table.

            Example:
            CREATE TABLE RelatedTableName (

            CONSTRAINT "FK_Name" FOREIGN KEY 
            (
                "{table_name}ID"
            ) REFERENCES "dbo"."{table_name}" (
                "{table_name}ID"
            )
            )
            GO
            table_name: RelatedTableName

            Example:
            ALTER TABLE RelatedTableName
            ADD CONSTRAINT [FK_Name] FOREIGN KEY 
            (
                [{table_name}ID]
            ) REFERENCES [dbo].[{table_name}] (
                [{table_name}ID]
            )
            GO
            table_name: RelatedTableName

            Output:
            table_name, table_name, table_name, ...
        """
    )
    query = prompt.format(table_name=table_name)
    ans = qa.run(query)
    print("Query: ", query)
    print("Answer: ", ans)
    list = ans.split(',')
    return list

In [173]:
print(fetch_foreign_keys_for_table("Employees"))

Getting FKs for Table:  Employees
Query:
            As a Microsoft SQL server programmer reading ANSI-SQL, list all the tables that have a foreign key foreign key constraint that references the Employees table.

            Example:
            CREATE TABLE RelatedTableName (

            CONSTRAINT "FK_Name" FOREIGN KEY
            (
                "EmployeesID"
            ) REFERENCES "dbo"."Employees" (
                "EmployeesID"
            )
            )
            GO
            table_name: RelatedTableName

            Example:
            ALTER TABLE RelatedTableName
            ADD CONSTRAINT [FK_Name] FOREIGN KEY
            (
                [EmployeesID]
            ) REFERENCES [dbo].[Employees] (
                [EmployeesID]
            )
            GO
            table_name: RelatedTableName

            Output:
            table_name, table_name, table_name, ...

Answer:  table_name: Territories, EmployeeTerritories
['table_name: Territories', ' EmployeeTerritories']